### ISSUE TITLE
Font not readable

### ISSUE THREAD

**Issue by shubhsin** [LUGM/lugm.github.io#11]
Please change the font to an easy to read one. 
Font size is way too small as compared to the bg.
Too much extra unneeded space in the sections as well.

**Comment by kartikarora** [comment]
Where? and suggest a font from Google Fonts

**Comment by shubhsin** [comment]
Roboto should be good. But the problem is for little text it's taking a lot of space above and below. Viewing on a 24 inch screen.

**Comment by kartikarora** [comment]
Read the source, its roboto. 

We'll see what can be done about spacing, please tell us which page.

**Comment by shubhsin** [comment]
musoc page coloured sections.

**Comment by shubhsin** [comment]
I see that the issue is resolved @kartikarora 
Closing this issue
