### ISSUE TITLE
Removing unnecessary clutter in code.

### ISSUE THREAD

**Issue by avikantz** [LUGM/lugm.github.io#4]
Removing clutter in [hackmanipal/index.html](https://github.com/LUGM/lugm.github.io/blob/master/hackmanipal/index.html), and corresponding styles and scripts.
The squarespace template contains a lot of unnecessary generated code which can be replaced by clean and elegant website code without making any sacrifice to performance.

Example:
- `<div class="sqs-block embed-block sqs-block-embed" data-block-json="&#123;&quot;hSize&quot;:null,&quot;floatDir&quot;:null,&quot;html&quot;:&quot;&lt;center&gt;\n&lt;div id=\&quot;countdown\&quot;&gt;\n&lt;iframe src=\&quot;https://freesecure.timeanddate.com/countdown/i5g58f8f/n250/cf12/cm0/cu4/ct0/cs0/ca0/co0/cr0/ss0/cacfff/cpcfff/pct/tcfff/fs200/szw576/szh243/iso2016-12-03T09:00:00\&quot; allowTransparency=\&quot;true\&quot; frameborder=\&quot;0\&quot; width=\&quot;393\&quot; height=\&quot;105\&quot;&gt;&lt;/iframe&gt;\n&lt;/div&gt;&lt;/center&gt;\n&quot;,&quot;resolvedBy&quot;:&quot;manual&quot;,&quot;resolved&quot;:true&#125;" data-block-type="22" id="block-yui_3_17_2_2_1478447187368_81457">`
could have one or two classes;
- The 20K line css is not entirely needed.

**Comment by kartikarora** [comment]
@avikantz Close it?
