### ISSUE TITLE
Countdown positioning on some mobile devices.

### ISSUE THREAD

**Issue by avikantz** [LUGM/lugm.github.io#7]
Countdown positioning could go for an update.

Currently it looks like ![this](https://cloud.githubusercontent.com/assets/7699509/21136029/fd8a602e-c149-11e6-8774-4ca7ad23bdbf.jpg) on some screen sizes, and like 
![this](https://cloud.githubusercontent.com/assets/7699509/21136050/0e2fc0ea-c14a-11e6-9ae9-d634209c46aa.jpg) others.

**Changes to be made**: either in single line like 
![this](https://cloud.githubusercontent.com/assets/7699509/21136163/803c80e2-c14a-11e6-877c-ff1fa8e6a6c7.jpg) or the 2x2 grid layout like ![this](https://cloud.githubusercontent.com/assets/7699509/21136050/0e2fc0ea-c14a-11e6-9ae9-d634209c46aa.jpg).

**Comment by kartikarora** [comment]
ye kya hai? @avikantz
